<?php
declare(strict_types=1);

// YahooFinance SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

YahooFinanceUtility::setRegistrar(function (YahooFinanceUtility $u): void {
    $u->clean = [YahooFinanceClean::class, 'call'];
    $u->done = [YahooFinanceDone::class, 'call'];
    $u->make_error = [YahooFinanceMakeError::class, 'call'];
    $u->feature_add = [YahooFinanceFeatureAdd::class, 'call'];
    $u->feature_hook = [YahooFinanceFeatureHook::class, 'call'];
    $u->feature_init = [YahooFinanceFeatureInit::class, 'call'];
    $u->fetcher = [YahooFinanceFetcher::class, 'call'];
    $u->make_fetch_def = [YahooFinanceMakeFetchDef::class, 'call'];
    $u->make_context = [YahooFinanceMakeContext::class, 'call'];
    $u->make_options = [YahooFinanceMakeOptions::class, 'call'];
    $u->make_request = [YahooFinanceMakeRequest::class, 'call'];
    $u->make_response = [YahooFinanceMakeResponse::class, 'call'];
    $u->make_result = [YahooFinanceMakeResult::class, 'call'];
    $u->make_point = [YahooFinanceMakePoint::class, 'call'];
    $u->make_spec = [YahooFinanceMakeSpec::class, 'call'];
    $u->make_url = [YahooFinanceMakeUrl::class, 'call'];
    $u->param = [YahooFinanceParam::class, 'call'];
    $u->prepare_auth = [YahooFinancePrepareAuth::class, 'call'];
    $u->prepare_body = [YahooFinancePrepareBody::class, 'call'];
    $u->prepare_headers = [YahooFinancePrepareHeaders::class, 'call'];
    $u->prepare_method = [YahooFinancePrepareMethod::class, 'call'];
    $u->prepare_params = [YahooFinancePrepareParams::class, 'call'];
    $u->prepare_path = [YahooFinancePreparePath::class, 'call'];
    $u->prepare_query = [YahooFinancePrepareQuery::class, 'call'];
    $u->graphql_body = [YahooFinanceGraphql::class, 'body'];
    $u->graphql_errors = [YahooFinanceGraphql::class, 'errors'];
    $u->result_basic = [YahooFinanceResultBasic::class, 'call'];
    $u->result_body = [YahooFinanceResultBody::class, 'call'];
    $u->result_headers = [YahooFinanceResultHeaders::class, 'call'];
    $u->transform_request = [YahooFinanceTransformRequest::class, 'call'];
    $u->transform_response = [YahooFinanceTransformResponse::class, 'call'];
});
